server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Pretty URLs: versuche URI, dann URI.html, sonst 404
        try_files $uri $uri.html =404;
    }
}